### ISSUE TITLE
No BT connection

### ISSUE THREAD

**Issue by BS-GIFHUB** [mariolukas/Bluetti_ESP32_Bridge#10]
I own a AC500 and with bluetti-mqtt I got very quick a connection. 

Now using the ESP32 I'm not getting an connection to my Bluetti station via BT. device id was checked 10 times and is fine. Connection to the mqtt server is fine but no connection the Bluetti.

The only change I did is to change in config.h

#ifndef BLUETTI_TYPE
  #define BLUETTI_TYPE BLUETTI_AC500
#endif

The problem seems to be timing in the BLE scan 

I changed in BTooth.cpp following values and then AC500 will be found:
  //pBLEScan->setInterval(1349);
  //pBLEScan->setWindow(449);
  //pBLEScan->setActiveScan(true);
  //pBLEScan->start(5, false);
  pBLEScan->setInterval(1349);
  pBLEScan->setWindow(5000);
  pBLEScan->setActiveScan(true);
  pBLEScan->start(40, false);

Now I'm trying to solve the next issue, because it is now found but not connected. it seems to be that the if cause doesn't work of the module BTooth.cpp

 /**
 * Scan for BLE servers and find the first one that advertises the service we are looking for.
 */
class BluettiAdvertisedDeviceCallbacks: public BLEAdvertisedDeviceCallbacks {
 /**
.......
if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(serviceUUID) && advertisedDevice.getName().compare(settings.bluetti_device_id)) {

Any ideas ?

Thanks Bernhard

**Comment by BS-GIFHUB** [comment]
I can test a connection with a manual setting 

of bluettiDevice = "B8:D6:1A:BF:32:EB"

but I don't the syntax how to overwrite 
bluettiDevice = new BLEAdvertisedDevice(advertisedDevice);

so that I'm able to use a fix id (not from you scan routine) which i got from "bluetti-mqtt --scan" using my PI.

So if you help I can test the issue with my AC500. 

Greetings Bernhard

**Comment by BS-GIFHUB** [comment]
Okay, 

now I installed the BLE Scanner from https://github.com/topics/ble-scanner to test my ESP32 Bluetooth and all is fine: BLUETTI was found and listed.

So now my conclusion is that something may be wrong with the used Bluetooth Library or routines because only few BT devices were listed and the signal from the BLUETTI isn't very strong (tested with a Bluetooth Scanner on my Iphone). So it doesn't connect. 

Any ideas to improve the Bluetooth performance in this module ?

Thanks 

Bernhard

**Comment by BS-GIFHUB** [comment]
Changed in BTooth.cpp

The if condition to 

if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(serviceUUID) ) {

Now I have the connection with the AC 500, but.......

no AC DC power status and command

**Comment by MartinRGH** [comment]
Hello Bernhard,

I have changed the line to

`    if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(serviceUUID) && (strcmp(advertisedDevice.getName().c_str(),settings.bluetti_device_id)==0) )
`
otherwise the device name is not checked at all and it will not be possible any more to have more than one devices.

Greetings,
Martin

**Comment by mariolukas** [comment]
Merged some of the PR's those should fix connection issues.
