### ISSUE TITLE
Trying to get it running for EB3A

### ISSUE THREAD

**Issue by giovanne123** [mariolukas/Bluetti_ESP32_Bridge#20]
Hi,
I'm trying to get it running for a EB3A.

- First question, is it right that the specific DEVICE_EB3A.h (https://github.com/mariolukas/Bluetti_ESP32_Bridge/blob/main/Bluetti_ESP32/DEVICE_EB3A.h) file is starting with:
#ifndef DEVICE_**AC300_H**
#define DEVICE_**AC300_H**

- I changed it to:
#ifndef DEVICE_EB3A_H
#define DEVICE_EB3A_H

- But at the moment I only get Wifi connected and Mqtt-Broker connected.

**But BL is not connecting:**
The Bluetti Bluetooth ID is the "EB3A2249........", right?
```
C:\Users\Max>bluetti-mqtt --scan
Scanning....
Found EB3A22490xxxxxxxxxx: address DD:E8:6C:xx:xx:xx
```

WebUI:
![image](https://user-images.githubusercontent.com/16689453/213174674-7ede9e1c-188a-4843-9466-97ba08161001.png)
Serial-Output (some text replaced with XXXXXX):

```
*wm:STA IP Address: 192.168.0.13

IP address: 
192.168.0.13
MDNS responder started
HTTP server started
BLE Advertised Device found: Name: EB3A2249XXXXXXXXXX, Address: dd:e8:6c:xx:xx:xx, manufacturer data: 424c424c554xxxxxx, serviceUUID: 0000ff00-0000-1000-8000-00805f9b34fb, rssi: -64
...
rssi: -75, serviceData: ���a���¢-�r
>89
Connecting to MQTT at: 192.168.0.111:1883
Connected to MQTT Server... 
```

Mqtt:
![image](https://user-images.githubusercontent.com/16689453/213175702-e550e86a-63a4-4eb9-a71f-350ff367f8e2.png)

**- Is there someone already using it with EB3A?
Have you done changes?**

**Comment by giovanne123** [comment]
Hm, flashed the fork: https://github.com/Seb0815/Bluetti_ESP32_Bridge
And this is directly working with EB3A
@Seb0815, Home Assistant Auto Discovery would be fine ;-)

![image](https://user-images.githubusercontent.com/16689453/213268052-eb5ae2ef-71f8-43ae-bc49-7a2dd512cb61.png)

![image](https://user-images.githubusercontent.com/16689453/213268442-474d3374-11fb-4612-9404-fb6a4f146732.png)

**Comment by giovanne123** [comment]
Update:
Connect to the EB3A with original from Mario is also working, when modifying the
BTooth.cpp:
Line 50:
from:
` if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(serviceUUID) && advertisedDevice.getName().compare(settings.bluetti_device_id)) {`
to:
 `if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(serviceUUID) && (strcmp(advertisedDevice.getName().c_str(),settings.bluetti_device_id)==0) ) {`

![image](https://user-images.githubusercontent.com/16689453/213393784-4f45187a-be83-4d9e-83c9-63cc2ccef11e.png)

@mariolukas, can you please update this to support these devices? (maybe test before if still working for your device)
@Seb0815, can you also update this in your fork? Maybe I will use this because of the nice WebUI ;-)
 
Now, I think details are missing in MQTT, see pictures for comparison with bluetti_mqtt:
- ac_output_on
- dc_output_on
- led_mode
- power_off
- eco_on
- eco_shutdown
- charging_mode
- power_lifting_on
- (need to test the possible commands)

additional nice features:
- (wifi retry if not connecting at boot)
- (HA discovery)
- (publish intervall changable by WebUI / command)
- (...)

ESP32-Bridge:
![image](https://user-images.githubusercontent.com/16689453/213394812-b25ac0ad-e1a1-41dc-9219-797752c0e114.png)

bluetti_mqtt (python):
![image](https://user-images.githubusercontent.com/16689453/213395512-291c66d9-a9ac-47a0-9208-49d7bb22b72c.png)

**Comment by mariolukas** [comment]
I will merge all open PR's this week, this will bring a new Webserver interface. Additionally i will fix the device definition in the header for the EB3A.

**Comment by giovanne123** [comment]
> I will merge all open PR's this week, this will bring a new Webserver interface. Additionally i will fix the device definition in the header for the EB3A.

Can you please also modify the 
BTooth.cpp: line 50
See above.

**Comment by mariolukas** [comment]
Yes i will review this.

**Comment by Seb0815** [comment]
@giovanne123 WLAN reconnect is already in my latest fork. I will create a PR as soon as @mariolukas merged all other PR's

**Comment by giovanne123** [comment]
> Yes i will review this.

 👍

**Comment by giovanne123** [comment]
> @giovanne123 WLAN reconnect is already in my latest fork. I will create a PR as soon as @mariolukas merged all other PR's

 👍

**Comment by areyoufserious** [comment]
i edited BTooth.cpp and DEVICE_EB3A_h as suggested
but stiil no connectiion

@giovanne123 asked
> The Bluetti Bluetooth ID is the "EB3A2249........", right?

i also would like to know

**Comment by giovanne123** [comment]
> i edited BTooth.cpp and DEVICE_EB3A_h as suggested but stiil no connectiion
> 
> @giovanne123 asked
> 
> > The Bluetti Bluetooth ID is the "EB3A2249........", right?
> 
> i also would like to know

Starting with the EB3A... would be right. With this it is connecting for me (see above screengrabs)

**Comment by mariolukas** [comment]
I am closing this because the initial issues should be fixed now. Reopen it if you have further issues related to this topic, otherwise create a new issue.

thanks !

**Comment by giovanne123** [comment]
Is ok. I will/have create/created new issues.
Was more collection for me what I will have to look for ;-)

**Comment by giovanne123** [comment]
> @giovanne123 WLAN reconnect is already in my latest fork. I will create a PR as soon as @mariolukas merged all other PR's

@Seb0815, I think you can create your PR regards to WLAN retry if not connected after first boot, because it isn't working [https://github.com/mariolukas/Bluetti_ESP32_Bridge/issues/26] after Mario has merged the PRs.
