### ISSUE TITLE
still no retry if first Wifi isn't connected after boot

### ISSUE THREAD

**Issue by giovanne123** [mariolukas/Bluetti_ESP32_Bridge#26]
Compiled lastest code from today (FW in WebUI 0.1.0), still no retry if first Wifi isn't connected after boot for EB3A:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
deactivate relais contact
Loading Values from EEPROM
*wm:AutoConnect
*wm:Connecting to SAVED AP: MY_WLAN
*wm:connectTimeout not set, ESP waitForConnectResult... 
*wm:AutoConnect: FAILED 
*wm:StartAP with SSID:  Bluetti_ESP32
*wm:AP IP address: 192.168.4.1
*wm:Starting Web Portal
ets Jun  8 2016 00:22:57

```

**Comment by Seb0815** [comment]
the code is already merged into main:

in BWifi.cpp 'initWifi' has setAutoReconnect defined and 'handleWebserver' has the needed code
`if (WiFi.status() != WL_CONNECTED) {
    Serial.println(F("WiFi is disconnected, try to reconnect..."));
    WiFi.disconnect();
    WiFi.reconnect();
    AddtoMsgView(String(millis()) + ": WLAN ERROR! try to reconnect");
    delay(1000);
  }
`
I haven't tested the current FW version yet, I'm still using my code - but the changes are already integrated

**Comment by Seb0815** [comment]
the initial connect should be handled by WiFiManager, maybe the version of the lib your are using is not the best way to support (I'm running 2.015-rc1)?

**Comment by giovanne123** [comment]
I'm using the same lib-version:

```
[env]
lib_deps =
    https://github.com/tzapu/WiFiManager/archive/refs/tags/v2.0.15-rc.1.zip
...
```

```
Scanning dependencies...
Dependency Graph
|-- WiFiManager @ 2.0.15-rc.1
|   |-- DNSServer @ 2.0.0
...
```

**Comment by giovanne123** [comment]
No further investigation, seems only I have the problem and therefore I will use the workaround to limit the AP timeout until reboot.
