### ISSUE TITLE
[Feature] Setting for MQTT Publish Intervall

### ISSUE THREAD

**Issue by giovanne123** [mariolukas/Bluetti_ESP32_Bridge#27]
Setting for MQTT Publish Intervall would be fine

e.g. in config.h
`#define MQTT_PUBLISH_INTERVALL 5
`

**Comment by AlexBurghardt** [comment]
There is already BLUETOOTH_QUERY_MESSAGE_DELAY in config.h.
This is the polling interval for BT data from the Bluetti Device and mqtt publishing is synchronized with that.
Change this, because an independent parameter for a mgtt publishing interval really does not make sense at all.

**Comment by giovanne123** [comment]
OK, fine
