### ISSUE TITLE
[Feature] keep alive messages

### ISSUE THREAD

**Issue by gerab** [mariolukas/Bluetti_ESP32_Bridge#36]
It would be nice to have some of the 'keep-alive' commands. At the moment, bluetti will turn off the main board on ~3-4 hours of inactivity. I'm sending a message to switch DC on/off every hour, and it works, but it makes DC outputs unusable.
The original code from warhammerkid contains the auto_sleep_mode command. Does it worth to be implemented? Even if it doesn't work, it may keep bluetti alive.

**Comment by gerab** [comment]
I missed that it's also implemented in PR, pulled the required changes and it seems to work, testing

**Comment by gerab** [comment]
As today was the first day without power outages and the station was primarily untouched physically and programmatically, only a scheduled task of switching the screen timeout occurred, and the station successfully fell asleep 😪, back to DC jerking. Still in search of a way to keep the station powered on indefinitely.

**Comment by SmokyBob** [comment]
@gerab from the behaviour you are experiencing seems like EcoMode is on.

My eb3a the board is directly connected to the dc usb output and it's on for days (goes off when I disconnect to upload a new version of the code), but I had to turn off EcoMode

**Comment by gerab** [comment]
> seems like EcoMode is o

nope, https://community.bluettipower.com/t/does-ac200max-auto-power-off/7807

**Comment by SmokyBob** [comment]
ah ok, from the forum post seems that ecomode is still "applied" if nothing is connected / using power.
That explains why it's staying on in my case, as I have the ESP32 board connected and using DC power.

**Comment by gerab** [comment]
There are two different things: "eco mode," which I believe will only switch off the inverter, and the other thing, which doesn't have a name or menu options in settings that will turn off the station entirely if idle. And yes, it doesn't bother you because you use DC constantly. And my station is just waiting for a command to put AC on while entirely idle.

**Comment by gerab** [comment]
It seems like there is no such option for AC200M, at least with the latest global firmware.
I will close until that might be changed.
