### ISSUE TITLE
Rename topics

### ISSUE THREAD

**Issue by gerab** [mariolukas/Bluetti_ESP32_Bridge#38]
It would be good to add a leading 0 to the topic name, like INTERNAL_CELL1_VOLTAGE => INTERNAL_CELL01_VOLTAGE. That'll remove the necessity of additional transformations to sort cells 1 to the last cell number. On a huge data set, it takes a significant amount of CPU time to rename and reorder them.

![image](https://user-images.githubusercontent.com/4732243/216125055-8180ce26-59de-44fe-981b-f1dbe0f7be1b.png)

**Comment by AlexBurghardt** [comment]
Good proposal. We can do that, but let Mario merge my 1st PR. Then I will do a 2nd one.
From which system is that visualization? Looks good.

**Comment by gerab** [comment]
Spent a day with Grafana. Thanks to your extended info data set I'm now able to build all the cool data and graphs, like how long ac200 would be living from battery. Super useful to have it here in Ukraine during the power outages to control my consumption. I'm really greatfull for your work, guys it significantly helps me to build a reliable power system. Check it out

![IMG_20230201_215631_593](https://user-images.githubusercontent.com/4732243/216149761-3faf3b3d-a4d0-43cc-9a45-4c011967aa84.jpg)
![IMG_20230201_215634_116](https://user-images.githubusercontent.com/4732243/216149771-c843abe5-9731-4c2a-993c-01721d6db7eb.jpg)

**Comment by AlexBurghardt** [comment]
Glad to read that the great work of Mario, all the other contributions and my own small improvements help you during this hard time. I wish you all the best and that this horror comes to a good end as soon as possible.

**Comment by gerab** [comment]
should be fixed as of now
