### ISSUE TITLE
Not connected to MQTT in Home Assistant

### ISSUE THREAD

**Issue by Dengor1984** [mariolukas/Bluetti_ESP32_Bridge#53]
ESP working, but no device BLUETTI in MQTT Home Assistant

![458DE46F-144F-4CB2-92C4-2E0AF1F3FC20](https://user-images.githubusercontent.com/28712832/220170036-3b6051aa-e5a4-45cc-b27c-194db840f60f.jpeg)

**Comment by Dengor1984** [comment]
![Uploading FBADB549-6D82-4BC1-93F6-F98830AFCB03.png…]()

**Comment by Dengor1984** [comment]
![EEACC2EA-CCC7-4D3F-B8B6-BB8A6631CE25](https://user-images.githubusercontent.com/28712832/220170827-a615483d-bcdd-4840-90c9-dba560002279.png)

**Comment by mariolukas** [comment]
The first image shows that the ESP32 is not connected to the MQTT server. The second shows that it is connected to the Server. 

Is this issue solved now? Or can you give a more detailed description of the current state?

**Comment by Dengor1984** [comment]
Issue is solved by my self - i have add all sensors by hand in mqtt.yaml and it's works.
But automatically it doesn't add AC200 with ALL sensors and  switches to mqtt!(

**Comment by Dengor1984** [comment]
Ps
ESP was connected to mqtt broker and send the topics, but mqtt don't respond it and as result no device in mqtt

**Comment by Dengor1984** [comment]
![Uploading DE0B8B4E-50AC-4653-BB6F-94FD5E489263.png…]()

**Comment by Dengor1984** [comment]
![7DE4C412-DD1E-44AB-9EFD-3274666E221E](https://user-images.githubusercontent.com/28712832/220447426-7edab96c-17c9-464e-9227-5ffdd2444ef4.png)

**Comment by Dengor1984** [comment]
Switch doesn't worked yet - maybe it with mistakes
